### ISSUE TITLE
process_exception method execute twice

### ISSUE THREAD

**Issue by ChouBaoDxs** [socotecio/django-socio-grpc#132]
version: 0.17.1
server code:
```python
from django_socio_grpc.exceptions import NotFound
raise NotFound()
```
client result:
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50052 {grpc_message:"", grpc_status:2, created_time:"2023-02-02T16:33:15.958708+08:00"}"
```
reason: process_exception repeated execute
other: version 0.16.16 is ok

**Comment by AMontagu** [comment]
Hello @ChouBaoDxs 

Just to be sure. Can I reproduce this by a unit test that check that in a service after a raise NotFound() the RPC error status should be not found ?

You think the issue come from process_exception being called twhice ? Are you in sync / async ? Unary or stream ?

**Comment by AMontagu** [comment]
@ChouBaoDxs Okay so the issue was only available outside unit test and I was able to reproduce it. It come from the middleware support.

https://github.com/socotecio/django-socio-grpc/pull/137 will fix it. We just need a little bit time to understand what will be implication in potential edge case.

Will be merged soon.

**Comment by AMontagu** [comment]
@ChouBaoDxs new beta version 0.18.0b8 available with the fix.
