### ISSUE TITLE
How to do a retrieve other then by primary key / ID ?

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc#192]
django-socio-grpc generates a proto-file for standard CRUD operations.
By default one can only do a **retrieve** by primary key / ID.
It seems that the code (in minxins.py) is also prepared for retrievals other then primary keys. 
But how is this done ?
E.g. if I have a model like:
```
class Book(models.Model):
  book_id = models.AutoField(primary_key=True)
  title =  models.TextField()
```
How would I retrieve a book by title or by book_id ? 
Could you please make an example that I can retrieve the book both by ID or by title ?
Thanks a lot.

**Comment by AMontagu** [comment]
Hello @markdoerr 

We based on DRF lookup field https://www.django-rest-framework.org/api-guide/generic-views/#attributes

It is also possible to customize the behavior by using lookup_request_field attribute or get_lookup_request_field in django_socio_grpc/generics.py but this is only if you have very specific behavior in your service like changing the request field depending on action.

We never really tested it as we don't need it so I can't assure you it is working correctly. 

If you have an issue with what I told you to use please send the code used and the issue and we will add an unit test on this.

**Comment by markdoerr** [comment]
Hello @AMontagu,
thanks for the fast answer.
If I understand it correctly, setting lookup_request_field to something different than "pk" would result in changing the default lookups for **all** lookups in a service. This is not, what I want, I just want to change the lookup in the **Retrieve** RPC call.

E.g. for the model above, I would like to retrieve book data 
```

# either by id
response = book_client.Retrieve(lbooks_pb2.BookRetrieveRequest(book_id=1))
# or by title
response = book_client.Retrieve(lbooks_pb2.BookRetrieveRequest(title='Les Miserable'))

```
How would I do this step-by-step ?
How would I specify this in the .proto file and in services.py ?

**Comment by AMontagu** [comment]
Hello @markdoerr 

Can you try in your service to define something like:

```
def get_lookup_request_field(self, queryset=None):
  if self.action == "Retrieve":
    return "custom_name_present_in_serializer"
  return super().get_lookup_request_field(queryset=queryset)
```

And tell me if it worked ?

**Comment by markdoerr** [comment]
Thanks, @AMontagu, 
for your proposal. 
Unfortunately it did not work. Partially because I do not know, how to call the Retrieve call with two different parameters (book_id or title). Should I use a oneof field in the .proto file ?

- I am currently trying to follow the 
pattern I found in your tests/sync_unit_test_model_service.py:

There you have something similar for Listing with extra Args:

```
class SyncUnitTestModelService(generics.ModelService, mixins.StreamModelMixin):
    queryset = UnitTestModel.objects.all().order_by("id")
    serializer_class = UnitTestModelSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["title", "text"]

    @grpc_action(
        request=[{"name": "archived", "type": "bool"}],
        response=UnitTestModelListExtraArgsSerializer,
    )
    def ListWithExtraArgs(self, request, context):
        # INFO - AM - 14/01/2022 - archived is an extra args in the custom request
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        count = 0
        if page is not None:
            queryset = page
            count = self.paginator.page.paginator.count
        # INFO - AM - 14/01/2022 - query_fetched_datetime is an extra args in the custom request
        serializer = UnitTestModelListExtraArgsSerializer(
            {"results": queryset, "query_fetched_datetime": datetime.now(), "count": count}
        )
        return serializer.message
```

So I am testing (with the book example above):

```
class BookService(generics.ModelService):
    queryset = Books.objects.all()
    serializer_class = DataProtoSerializer

    @grpc_action(
        request=[{"title": "title", "type": "string"}],
        response=BookByNameProtoSerializer
    )
    def RetrieveByName(self, request, context):
       
        queryset = self.filter_queryset(self.get_queryset()) # this does not apply any filters, so I get all titles = not working correctly

    # this is working:    queryset = Data.objects.filter(title=request.title)

        for item in queryset:
            print("##### +++++ queryset:", item.title)

        serializer = BookByNameProtoSerializer(
             # I do not know, what parameters I have to supply here
         )
        return serializer.message

```
and try to call it by:

```
# or by title
response = book_client.RetrieveByTitle(books_pb2.BookRetrieveRequest(title='Les Miserables'))
```
I can call the remote procedure - it is executed, but the response is still not correct (also because I still do not understand, with which parameters I need to call the serializer and how the serializer should look like - how do I transfer the queryset to the serializer, e.g.. ?)
The filter in the above example does not work (only, if I use the second variant, which I commented out).

What would be the correct call of the serializer ? How would the serializer look like ?

**Comment by AMontagu** [comment]
Okay. 
So I indeed the workaround is to define a new method. I thought you wanted to keep the default Retrieve with an other lookup_field.

To make a custom retrieve is possible like:
```
@grpc_action(
       request=[{"title": "title", "type": "string"}],
        response=BookByNameProtoSerializer
    )
    def RetrieveByTitle(self, request, context):
        # HERE HANDLE 404 OR MULTILE OBJECTS RETURNED IF TITLE DOT NOT HAVE UNICITY CONSTRAINT ON BOOK TABLE
        instance = Books.objects.get(title=request.title)
        serializer = self.get_serializer(instance)
        return serializer.message
```

**Comment by markdoerr** [comment]
Merci beaucoup, @AMontagu,

this was the missing piece ! 
Now it is working ;)

Thanks a lot for your help !!!

(Maybe we put this into the documentation - I think that many people would be glad, since it illustrates how to add additional custom RPCs )

**Comment by AMontagu** [comment]
Its all here: https://socotecio.github.io/django-socio-grpc/generate_proto/#adding-custom-method-decorator

But indeed we will improve with more full example.

**Comment by markdoerr** [comment]
@AMontagu,
nonetheless I still would also be interested in a solution without the workaround, like you had it in mind :) 
Any ideas, how to achieve that ?

**Comment by AMontagu** [comment]
@markdoerr need some time to test it. I have an hour this afternoon to look for it

**Comment by markdoerr** [comment]
> Its all here: https://socotecio.github.io/django-socio-grpc/generate_proto/#adding-custom-method-decorator
> 
> But indeed we will improve with more full example.

Yes indeed, without a full example this can only be understood by a few blessed people ;)

**Comment by AMontagu** [comment]
Hi @markdoerr  

Look like what I proposed is working. Please take a look at: https://github.com/socotecio/django-socio-grpc/tree/issue/exampleCustomRetrieve changes compared to master

**Comment by markdoerr** [comment]
Hi @AMontagu,
looks elegant :) - thanks for making this example.
I still do not understand, where it is determined, if the "title" or "id" is used as lookup_field. 

In your get_lookup_request_field() function you always return "title", if action is "Retrieve". 
Where happens the decision: if *id* is provided, use *id* as lookup_field, elseif *title* is provided, use the title ?
Can you point me to the place where this decision happens ?

**Comment by markdoerr** [comment]
Is this some magics, coming from *django-filter* ?
To run this example, *django-filter* needs to be installed.

**Comment by AMontagu** [comment]
Hello @markdoerr 

I think there is a misunderstandanding in the REST API logic. 
We copy the behavior of DRF and adapt it to gRPC.
In REST best practices you can only retrieve by one attribute in a get request with an URL attribute. Ex:
test.com/api/book/1 or test.com/api/book/Les%20Miserables depending of the lookup_field and the lookup_url_kwargs explained here: https://www.django-rest-framework.org/api-guide/generic-views/#attributes

It is a bad practice to be able to retrieve on the same url with two different attributes. This is not supported by DRF because it's a bad practices so we do not support it by default either even if we can think about a retrieve based on all paramaters that are present in the request.

I give you an example, the book 1984 have the title 1984. if you send it to the back and a book with the id 1984 exist what book will be retrievied ? The one with the id, the tittle or both ?

It is recommended to use only a uniq database column for retrieving and indeed use filter on the list to fetch specific elements OR creating a new specific endpoint that does what you want but not the default Retrieve one. 

In my working example I changed the Id by the title. So the retrieve was not working by Id, only by title.
All the logic is done by DRF logic using the lookup_field.

Basically in all the code we use `get_object`(https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/generics.py#L92) to get the good object (from drf: https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py#L79) based on argument.
See: https://www.django-rest-framework.org/api-guide/generic-views/#get_objectself

The only difference in DSG is that as we also need the field name to generate the proto we refactored the DRF logic of retrieving the good name in `get_lookup_request_field` to be able to call it without getting the all object.  

So by overriding get_lookup_request_field you tell them that if the action is retrieve the column in database to use for retrieving is title and not the primary key.
Note that this is an advance behavior and not a best practice as you should have the same column for retrieving/deleting/updating to avoid user confusion

**Comment by markdoerr** [comment]
Thanks a lot for this excellent explanation, @AMontagu,
with every piece I learn more and more about the design of the whole package.
I hope, we can transform this information into good documentation in the future. 
DCG has a lot of potential, many might not know :)
